extends Node

enum GameStates {RUNNING, PAUSED}

enum CursorStates {UNSELECTED, SELECTED}
enum PlacerStates {VALID, SOFT_INVALID, HARD_INVALID}
enum MovableStates {NONE, CANPUSHNORTH, CANPUSHEAST, CANPUSHSOUTH, CANPUSHWEST, CANPULLNORTH, CANPULLEAST, CANPULLSOUTH, CANPULLWEST}

var game_state = GameStates.RUNNING
